"""
Django settings for newNovo project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2y-%f!-e)h9ct#*-&4@g*tyja%glr5w054=a(27777fh4x@*9k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['xn--36-6kch5aj8bbq6g.xn--p1ai', 'http://127.0.0.1', 'http://localhost', 'http://127.0.0.1:8000' , '127.0.0.1']

CSRF_TRUSTED_ORIGINS = ['https://xn--36-6kch5aj8bbq6g.xn--p1ai', 'http://127.0.0.1', 'http://localhost', 'http://127.0.0.1:8000']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'corsheaders',
    'main'
]

# Custom user model
AUTH_USER_MODEL = 'main.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOWED_ORIGINS = ('https://kvartiri36.ru', 'http://127.0.0.1', 'http://localhost')

ROOT_URLCONF = 'newNovo.urls'

TEMPLATES = [{
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [],
    # 'APP_DIRS': True, TODO: uncomment on deploy
    'OPTIONS': {
        'context_processors': [
            'django.template.context_processors.debug',
            'django.template.context_processors.request',
            'django.contrib.auth.context_processors.auth',
            'django.contrib.messages.context_processors.messages',
        ],
        # TODO: remove on deploy
        'loaders':  [
            "django.template.loaders.filesystem.Loader",
            "django.template.loaders.app_directories.Loader",
        ]
    },
}]

WSGI_APPLICATION = 'newNovo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'new-site-dev',
        'USER': 'postgres',
        'PASSWORD': 'admin',
        'HOST': 'localhost',
        'PORT': '5433',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
LANGUAGE_CODE = 'ru-RU'
TIME_ZONE = 'Europe/Moscow'
USE_I18N = True
USE_L10N = True
USE_TZ = True
USE_THOUSAND_SEPARATOR = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  # Папка, откуда брать статику при разработке

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Куда загружаются медиа-файлы

# если используешь отдельные каталоги
BUILDS_ROOT = os.path.join(BASE_DIR, 'static', 'buildings')
BUILDS_URL = '/static/buildings/'

ARTICLES_ROOT = os.path.join(BASE_DIR, 'static', 'articles')
ARTICLES_URL = '/static/articles/'

PARTNERS_ROOT = os.path.join(BASE_DIR, 'static', 'partners')
ARTICLES_URL = '/static/partners/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Источник комплекса
SOURCE_CHOICES = (
    ('raz', 'Развитие'),
    ('pv', 'Первичка'),
    ('nmarket', 'НМаркет'),
    ('raw', 'Ручные')
)

YANDEX_MAP_KEY = '0bbea9cc-3ade-4d3d-a262-cbe848e25da8'

CRM_TOKEN = '53cr3t43y'
CRM_URL = 'https://crm.xn--36-6kch5aj8bbq6g.xn--p1ai'

# Telegram BOT key (если вы новый разраб, то попросите передать вам бота у прошлого)
TELEGRAM_BOT_KEY = '6746506307:AAGLk6oOkplmyZhPbCRdNBPe5gim_DUbNTE'
TELEGRAM_CHAT_ID = '-1002008808156'  # беседа "Новостройки Воронеж согласование 2

# Куда кидать будем после авторизации
LOGIN_REDIRECT_URL = '/profile/'
LOGIN_URL = '/profile/login/'

REGISTRATION_SALT = '5u93rm39453cr3t541t'
ACCOUNT_ACTIVATION_DAYS = 3

# Настройки почты
DEFAULT_FROM_EMAIL = 'info@квартиры36.рф'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.mail.selcloud.ru'
EMAIL_PORT = 1126
EMAIL_TIMEOUT = 15
EMAIL_HOST_USER = '1308'
EMAIL_HOST_PASSWORD = 'ivOuexzXo1tnUP60'