# Generated by Django 5.0 on 2024-01-16 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_complex_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='description',
        ),
        migrations.RemoveField(
            model_name='build',
            name='name',
        ),
    ]
