# Generated by Django 5.0 on 2024-01-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_build_description_remove_build_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='complex',
            name='suffix',
            field=models.TextField(blank=True, help_text='Будет видно только на авито', null=True, verbose_name='Суффикс к описанию'),
        ),
    ]
