# Generated by Django 5.0 on 2024-01-24 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_complex_suffix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complex',
            name='suffix',
        ),
    ]
