# Generated by Django 5.0 on 2024-02-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_complex_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='mortgage',
            field=models.BooleanField(default=True, help_text='Для циана', verbose_name='Доступна ли ипотека?'),
        ),
    ]
