# Generated by Django 5.0 on 2024-02-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_build_mortgage'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='cian_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Циан ID'),
        ),
        migrations.AddField(
            model_name='build',
            name='domclick_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ДомКлик ID'),
        ),
    ]
