# Generated by Django 5.0 on 2024-02-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_build_cian_id_build_domclick_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='complex',
            name='cian_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Циан ID'),
        ),
        migrations.AddField(
            model_name='complex',
            name='domclick_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ДомКлик ID'),
        ),
    ]
