# Generated by Django 5.0 on 2024-02-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_complex_cian_id_complex_domclick_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='build',
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='Статья', max_length=50, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
