# Generated by Django 5.0 on 2024-02-19 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_article_build_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='Избранное?'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='complex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.complex', verbose_name='Жилой комплекс'),
        ),
    ]
