# Generated by Django 5.0 on 2024-02-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_promo_favorite_alter_promo_complex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='yandex_internal_id',
        ),
        migrations.AddField(
            model_name='build',
            name='yandex_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Yandex ID'),
        ),
        migrations.AddField(
            model_name='complex',
            name='yandex_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Yandex ID'),
        ),
    ]
