# Generated by Django 5.0 on 2024-03-15 11:34

import main.models.bonus
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_flat_yandex_internal_id_build_yandex_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(help_text='Фото формата .png, .jpg, .jpeg. Не более 2мб', upload_to=main.models.bonus.directory_path, verbose_name='Фото')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('size', models.IntegerField(default=0, verbose_name='Размер скидки')),
                ('size_type', models.CharField(choices=[('rubles', 'Рубли'), ('dollars', 'Доллары'), ('euros', 'Евро'), ('percentage', 'Проценты')], default='rubles', max_length=11, verbose_name='Тип')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'бонус',
                'verbose_name_plural': 'бонусы',
                'db_table': 'bonuses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Адрес электронной почты'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(error_messages={'unique': 'Пользователь с данным телефоном уже существует'}, max_length=18, unique=True, verbose_name='Номер телефона'),
        ),
    ]
