# Generated by Django 5.0 on 2024-03-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_bonus_user_email_user_name_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='complex',
            name='description_alternative',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (альтернативное)'),
        ),
    ]
