# Generated by Django 5.0 on 2024-03-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_buyobject_objectcommerce_objectflat_objecthouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyobject',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='Кто создал'),
            preserve_default=False,
        ),
    ]
