# Generated by Django 5.0 on 2024-04-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_buyobject_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyobject',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано?'),
        ),
    ]
