# Generated by Django 5.0 on 2024-04-02 11:19

import django.db.models.deletion
#import main.models.object_photo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_buyobject_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                #('photo', models.FileField(help_text='Фото формата .png, .jpg, .jpeg. Не более 2мб', upload_to=main.models.object_photo.directory_path, verbose_name='Фото')),
                ('obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.buyobject', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'фото объявления',
                'verbose_name_plural': 'фотографии объявлений',
                'db_table': 'object_photo',
            },
        ),
    ]
