# Generated by Django 5.0 on 2024-04-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_objectphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Категория'),
        ),
    ]
