# Generated by Django 5.0 on 2024-05-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_flat_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyobject',
            name='avito_id',
            field=models.IntegerField(default=0, verbose_name='Avito ID'),
        ),
        migrations.AddField(
            model_name='buyobject',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='buyobject',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Видео объекта'),
        ),
    ]
