# Generated by Django 5.0 on 2024-05-17 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_buyobject_avito_id_buyobject_url_buyobject_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyobject',
            name='floors',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Этажи'),
        ),
        migrations.AlterField(
            model_name='buyobject',
            name='object_type',
            field=models.CharField(blank=True, choices=[('Дом', 'Дом'), ('Дача', 'Дача'), ('Коттедж', 'Коттедж'), ('Таунхаус', 'Таунхаус'), ('Поселений (ИЖС)', 'Поселений (ИЖС)'), ('Сельхозназначения (СНТ, ДНП)', 'Сельхозназначения (СНТ, ДНП)'), ('Промназначения', 'Промназначения'), ('Личное подсобное хозяйство (ЛПХ)', 'Личное подсобное хозяйство (ЛПХ)')], max_length=32, null=True, verbose_name='Тип объекта'),
        ),
        migrations.AlterField(
            model_name='buyobject',
            name='property_rights',
            field=models.CharField(choices=[('Собственник', 'Собственник'), ('Посредник', 'Посредник')], default='Посредник', max_length=12, verbose_name='Право собственности'),
        ),
        migrations.AlterField(
            model_name='buyobject',
            name='square',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='buyobject',
            name='user_id',
            field=models.IntegerField(default=0, help_text='0 указывается, если объявление создано автовыгрузкой', verbose_name='Кто создал'),
        ),
    ]
