# Generated by Django 5.0 on 2024-05-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_buyobject_floors_alter_buyobject_object_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyobject',
            name='avito_id',
            field=models.BigIntegerField(default=0, verbose_name='Avito ID'),
        ),
    ]
