# Generated by Django 5.0 on 2024-05-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_buyobject_avito_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectflat',
            name='room_type',
            field=models.CharField(blank=True, choices=[('Изолированные', 'Изолированные'), ('Смежные', 'Смежные')], max_length=14, null=True, verbose_name='Тип комнат'),
        ),
    ]
