# Generated by Django 5.0 on 2024-05-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_objectflat_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectflat',
            name='deal_type',
            field=models.CharField(blank=True, choices=[('Прямая продажа', 'Прямая продажа'), ('Альтернативная', 'Альтернативная')], max_length=15, null=True, verbose_name='Тип сделки'),
        ),
    ]
