# Generated by Django 5.0 on 2024-05-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_objectflat_deal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectlease',
            name='appliance',
            field=models.JSONField(blank=True, null=True, verbose_name='Бытовая техника'),
        ),
        migrations.AddField(
            model_name='objectlease',
            name='furniture',
            field=models.JSONField(blank=True, null=True, verbose_name='Мебель'),
        ),
    ]
