# Generated by Django 5.0 on 2024-05-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_objectlease_appliance_objectlease_furniture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectflat',
            name='room_type',
            field=models.JSONField(blank=True, null=True, verbose_name='Тип комнат'),
        ),
    ]
