# Generated by Django 5.0 on 2024-05-17 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_objectflat_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectcommerce',
            name='place_type',
            field=models.CharField(blank=True, choices=[('Закреплённое место', 'Закреплённое место'), ('Плавающее место', 'Плавающее место'), ('Отдельный кабинет', 'Отдельный кабинет')], max_length=19, null=True, verbose_name='Статус рабочего места'),
        ),
        migrations.AlterField(
            model_name='objectcommerce',
            name='places_in_room',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(1000)], verbose_name='Количество рабочих мест в кабинете'),
        ),
        migrations.AlterField(
            model_name='objectcommerce',
            name='room_area',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(1000)], verbose_name='Площадь кабинета'),
        ),
    ]
