# Generated by Django 5.0 on 2024-05-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_objectcommerce_place_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectlease',
            name='l_type',
            field=models.CharField(blank=True, choices=[('На длительный срок', 'На длительный срок'), ('Посуточно', 'Посуточно')], max_length=19, null=True, verbose_name='Тип аренды'),
        ),
    ]
