# Generated by Django 5.0 on 2024-05-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_objectlease_l_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectlease',
            name='utility_meters',
            field=models.CharField(choices=[('Оплачивается арендатором', 'Оплачивается арендатором'), ('Оплачивается собственником', 'Оплачивается собственником')], default='Оплачивается арендатором', max_length=27, verbose_name='Оплата по счетчикам'),
        ),
    ]
