# Generated by Django 5.0 on 2024-05-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_objectlease_utility_meters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectlease',
            name='other_utilities',
            field=models.CharField(choices=[('Оплачивается арендатором', 'Оплачивается арендатором'), ('Оплачивается собственником', 'Оплачивается собственником')], default='Оплачивается арендатором', help_text='Отопление, капремонт, вывоз мусора, другие', max_length=27, verbose_name='Другие ЖКУ'),
        ),
    ]
