# Generated by Django 5.0 on 2024-05-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_objectlease_other_utilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complex',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='complex',
            name='church',
        ),
        migrations.RemoveField(
            model_name='complex',
            name='fitness',
        ),
        migrations.RemoveField(
            model_name='complex',
            name='health',
        ),
        migrations.RemoveField(
            model_name='complex',
            name='kindergarten',
        ),
        migrations.RemoveField(
            model_name='complex',
            name='magazine',
        ),
        migrations.RemoveField(
            model_name='complex',
            name='school',
        ),
        migrations.AlterField(
            model_name='buyobject',
            name='rooms',
            field=models.CharField(choices=[('Студия', 'Студия'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10 и более', '10 и более'), ('Своб. Планировка', 'Своб. Планировка')], max_length=16, verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='objectlease',
            name='deposit',
            field=models.CharField(choices=[('Без залога', 'Без залога'), ('0,5 месяца', '0,5 месяца'), ('1 месяц', '1 месяц'), ('1,5 месяца', '1,5 месяца'), ('2 месяца', '2 месяца'), ('2,5 месяца', '2,5 месяца'), ('3 месяца', '3 месяца')], verbose_name='Залог'),
        ),
    ]
