# Generated by Django 5.0 on 2024-05-30 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_objectstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectstat',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.buyobject', verbose_name='Объект'),
        ),
    ]
