# Generated by Django 5.0 on 2024-06-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_bonus_address_bonus_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Название поля')),
                ('value', models.TextField(verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'параметры объявления у объекта',
                'verbose_name_plural': 'параметры объявлений у объектов',
                'db_table': 'object_field',
                'managed': False,
            },
        ),
    ]
