# Generated by Django 5.0 on 2024-06-30 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_objectfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyobject',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='buyobject',
            name='category',
            field=models.CharField(blank=True, choices=[('Квартиры', 'Квартиры'), ('Дом, дачи, коттеджи', 'Дом, дачи, коттеджи'), ('Земельные участки', 'Земельные участки'), ('Коммерческая недвижимость', 'Коммерческая недвижимость')], max_length=26, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='buyobject',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='buyobject',
            name='operation_type',
            field=models.CharField(blank=True, choices=[('Продам', 'Продам'), ('Сдам', 'Сдам')], max_length=7, null=True, verbose_name='Тип операции'),
        ),
        migrations.AlterField(
            model_name='buyobject',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='buyobject',
            name='property_rights',
            field=models.CharField(blank=True, choices=[('Собственник', 'Собственник'), ('Посредник', 'Посредник')], default='Посредник', max_length=12, null=True, verbose_name='Право собственности'),
        ),
        migrations.AlterField(
            model_name='buyobject',
            name='rooms',
            field=models.CharField(blank=True, choices=[('Студия', 'Студия'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10 и более', '10 и более'), ('Своб. Планировка', 'Своб. Планировка')], max_length=16, null=True, verbose_name='Количество комнат'),
        ),
    ]
