# Generated by Django 5.0 on 2024-09-16 10:40

import django.core.validators
import django.db.models.deletion
import main.models.realty.flat_photo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_buyobject_address_alter_buyobject_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(help_text='Фото формата .png, .jpg, .jpeg. Не более 2мб', upload_to=main.models.realty.flat_photo.directory_path, verbose_name='Фото')),
                ('sort', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'фото объявления',
                'verbose_name_plural': 'фотографии объявлений',
                'db_table': 'flat_photo',
            },
        ),
        migrations.CreateModel(
            name='FlatPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Дата создания')),
                ('price', models.FloatField(default=0, verbose_name='Стоимость квартиры')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'история цен по квартире',
                'verbose_name_plural': 'истории цен по квартирам',
                'db_table': 'flat_history_prices',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avito_id', models.IntegerField(verbose_name='Avito ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Если описание квартир перезаписывать не надо, то лучше оставить пустым', null=True, verbose_name='Описание')),
                ('region', models.CharField(blank=True, max_length=60, null=True, verbose_name='Регион')),
                ('city', models.CharField(blank=True, max_length=60, null=True, verbose_name='Город')),
                ('material', models.CharField(blank=True, choices=[('Кирпичный', 'Кирпичный'), ('Панельный', 'Панельный'), ('Блочный', 'Блочный'), ('Монолитный', 'Монолитный'), ('Монолитно-кирпичный', 'Монолитно-кирпичный')], max_length=20, null=True, verbose_name='Материал стен')),
                ('floors', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество этажей')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено?')),
                ('hide', models.BooleanField(default=False, verbose_name='Спрятано?')),
                ('domclick_hide', models.BooleanField(default=True, verbose_name='Спрятано на домклик?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'объект',
                'verbose_name_plural': 'объекты',
                'db_table': 'objects',
            },
        ),
        migrations.RemoveField(
            model_name='build',
            name='complex',
        ),
        migrations.RemoveField(
            model_name='build',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='build',
        ),
        migrations.RemoveField(
            model_name='objecthouse',
            name='obj',
        ),
        migrations.RemoveField(
            model_name='objectstat',
            name='obj',
        ),
        migrations.RemoveField(
            model_name='objectcommerce',
            name='obj',
        ),
        migrations.RemoveField(
            model_name='objectflat',
            name='obj',
        ),
        migrations.RemoveField(
            model_name='objectphoto',
            name='obj',
        ),
        migrations.RemoveField(
            model_name='objectlease',
            name='obj',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='complex',
        ),
        migrations.RemoveField(
            model_name='historyflat',
            name='flat',
        ),
        migrations.DeleteModel(
            name='ObjectField',
        ),
        migrations.AlterModelOptions(
            name='developer',
            options={'verbose_name': 'застройщик', 'verbose_name_plural': 'застройщики'},
        ),
        migrations.AlterModelOptions(
            name='flat',
            options={'verbose_name': 'квартира', 'verbose_name_plural': 'квартиры'},
        ),
        migrations.RenameField(
            model_name='flat',
            old_name='kitchen_square',
            new_name='kitchen_space',
        ),
        migrations.RenameField(
            model_name='flat',
            old_name='living_square',
            new_name='living_space',
        ),
        migrations.RenameField(
            model_name='flat',
            old_name='total_square',
            new_name='square',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='balcony',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='bathroom_unit',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='category',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='type',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='views',
        ),
        migrations.AddField(
            model_name='flat',
            name='apartment_number',
            field=models.CharField(default=0, max_length=10, verbose_name='Номер квартиры'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flat',
            name='domclick_hide',
            field=models.BooleanField(default=False, verbose_name='Спрятано на домклик?'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='decoration',
            field=models.CharField(choices=[('Без отделки', 'Без отделки'), ('Предчистовая', 'Предчистовая'), ('Чистовая', 'Чистовая')], default='Без отделки', max_length=13, verbose_name='Отделка'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='floor',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='Спрятано?'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='import_id',
            field=models.BigIntegerField(default=0, verbose_name='Import ID'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено?'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='rooms',
            field=models.CharField(choices=[('Студия', 'Студия'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10 и более', '10 и более'), ('Своб.планировка', 'Своб.планировка')], default='1', verbose_name='Количество комнат'),
        ),
        migrations.AddField(
            model_name='flatphoto',
            name='flat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.flat', verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='flatpricehistory',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.flat', verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='object',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.developer', verbose_name='Застройщик'),
        ),
        migrations.AddField(
            model_name='object',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.object', verbose_name='Комплекс'),
        ),
        migrations.AddField(
            model_name='flat',
            name='obj',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.object', verbose_name='Объект'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promo',
            name='obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.object', verbose_name='Жилой комплекс'),
        ),
        migrations.DeleteModel(
            name='Build',
        ),
        migrations.DeleteModel(
            name='ObjectHouse',
        ),
        migrations.DeleteModel(
            name='ObjectStat',
        ),
        migrations.DeleteModel(
            name='ObjectCommerce',
        ),
        migrations.DeleteModel(
            name='ObjectFlat',
        ),
        migrations.DeleteModel(
            name='ObjectPhoto',
        ),
        migrations.DeleteModel(
            name='BuyObject',
        ),
        migrations.DeleteModel(
            name='ObjectLease',
        ),
        migrations.DeleteModel(
            name='Complex',
        ),
        migrations.DeleteModel(
            name='HistoryFlat',
        ),
    ]
