# Generated by Django 5.0 on 2024-09-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_flatphoto_flatpricehistory_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='alternative_description',
            field=models.TextField(blank=True, help_text='Если описание квартир перезаписывать не надо, то лучше оставить пустым', null=True, verbose_name='Описание'),
        ),
    ]
