# Generated by Django 5.0 on 2024-10-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_object_alternative_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='show',
            field=models.BooleanField(default=False, verbose_name='Принудительно отображать?'),
        ),
    ]
