# Generated by Django 5.1.5 on 2025-05-28 16:12

import django.db.models.deletion
import main.models.article_photo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_object_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(help_text='Фото формата .png, .jpg, .jpeg. Не более 2мб', upload_to=main.models.article_photo.directory_path, verbose_name='Фото')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.article', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'фото новости',
                'verbose_name_plural': 'фотография новости',
                'db_table': 'article_photo',
            },
        ),
    ]
