# Generated by Django 5.1.5 on 2025-05-28 17:06

import django.db.models.deletion
import main.models.partners.partner_photo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_articlephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Дата создания')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон')),
                ('discount', models.FloatField(blank=True, null=True, verbose_name='Скидка')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалена?')),
            ],
            options={
                'verbose_name': 'партнёр',
                'verbose_name_plural': 'партнёры',
                'db_table': 'partners',
            },
        ),
        migrations.CreateModel(
            name='PartnerPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(help_text='Фото формата .png, .jpg, .jpeg. Не более 2мб', upload_to=main.models.partners.partner_photo.directory_path, verbose_name='Фото')),
                ('sort', models.IntegerField(default=0, verbose_name='Порядок')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.partner', verbose_name='Партнёр')),
            ],
            options={
                'verbose_name': 'фото партнёра',
                'verbose_name_plural': 'фотографии партнёра',
                'db_table': 'partner_photo',
            },
        ),
    ]
