# Generated by Django 5.2.1 on 2025-05-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_promo_end_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='flats_on_promo',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество квартир по акции'),
        ),
    ]
