# Generated by Django 5.2.1 on 2025-05-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_promo_flats_on_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='type',
            field=models.CharField(blank=True, choices=[('Flat', 'Квартира'), ('Commerce', 'Коммерческая недвижимость'), ('House', 'Дом'), ('Elite', 'Элитная недвижимость')], max_length=60, null=True, verbose_name='Тип'),
        ),
    ]
